version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://mysecuredemosite77
      - echo "invalidating cloudFront cache"
      - aws cloudfront create-invalidation --distribution-id E15RQFR6R54J2T --paths "/*"